version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine
    # restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  api-service:
    build:
      context: ./api-service
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${API_PORT}
    depends_on:
      - postgres
      - stock-service
    networks:
      - app-network
    restart: always

  stock-service:
    build:
      context: ./stock-service
    ports:
      - "${STOCK_PORT}:${STOCK_PORT}"
    environment:
      - NODE_ENV=development
      - PORT=${STOCK_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
